[dependency-groups]
# `pip` supports `dependency-groups` from version 25.1. Usage:
#
#   pip install --group build
#   pip install --group test
#
# References:
#
#   https://github.com/pypa/pip/issues/12963
#   https://github.com/pypa/pip/pull/13065
#
# You only need test dependencies if you are running unit tests:
test = [
    "flake8",
    "black",
    "isort",
    "bandit",
    "coverage",
    "pytest",
]

[tool.bandit]
assert_used = { skips = [ "*/test_*.py" ] }

[tool.isort]
multi_line_output = 3  # https://pycqa.github.io/isort/docs/configuration/options.html#multi-line-output
include_trailing_comma = true  # require trailing comma at the end of a list of imports in parentheses
line_length = 120  # https://pycqa.github.io/isort/docs/configuration/options.html#line-length

[tool.black]
line-length = 120

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "mneia_project.settings"
